server.port=${PORT:8080}

# Supabase PostgreSQL připojení
spring.datasource.url=jdbc:postgresql://db.cfahcstxeowvbpdzxjkk.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=M8WBem45XP+vS9i
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate nastavení (tabulky se vytvoří same, data se nemažou)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect