server.port=${PORT:8080}

# Supabase Connection Pooler
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.cfahcstxeowvbpdzxjkk
spring.datasource.password=hnnmaNWPEaZ54z6O
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate nastavení
spring.jpa.hibernate.ddl-auto=update